version: "3"
services:
    nginx:
        restart: always
        image: nginx:1.13
        volumes:
            - ./nginx/autoclassweb_nginx.conf:/etc/nginx/conf.d/default.conf
            - flaskapp-static:/www/static
            - /tmp/autoclassweb/logs:/var/log/nginx
        ports:
            - 8000:80
        depends_on:
            - flaskapp


    flaskapp:
        restart: always
        build: .
        volumes:
            - flaskapp-static:/app/flaskapp/static
            - /tmp/autoclassweb/results:/app/results
        env_file: .env
        environment:
            FLASK_DEBUG: 1
        command: "pipenv run gunicorn --config gunicorn.conf flaskapp:app"

volumes:
    flaskapp-static:
