version: "2"
services:
    nginx:
        restart: always
        build: ./nginx
        volumes:
            - /www/static
        ports:
            - 8000:80
        depends_on:
            - flaskapp
        volumes_from:
            - flaskapp

    flaskapp:
        restart: always
        build: .
        ports:
            - 5000
        volumes:
            - /app/flaskapp/static
        env_file: .env
        environment:
            FLASK_DEBUG: 1
        command: "pipenv run gunicorn --config gunicorn.conf flaskapp:app"
